//       Autogenerated Class From XMLToModel         //
using System;
using System.Collections.Generic;
using System.Linq;

namespace HubXLookUps
{
	/// <summary>
	/// 
	/// </summary>
	public class EmployeeJobCodes
	{
		/// <summary>
		/// 
		/// </summary>
		public string JobClsCd { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string RecEffSttDt { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string RecStsCd { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string JobClsCdDscTe { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string JobFctCd { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string PayBssTypCd { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string EmpOpTypCd { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string JobUnnEmpReqIr { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string JobPhyExmReqIr { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string JobSafAwdElgIr { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string JobEocOccCgyCd { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string JobGrpCd { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string EmpFlsJobClsCd { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string CdaNtlOccCsfCd { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string WagCd { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string BsuGrpTe { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string MgrLvlCd { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string JtlAbrNa { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string JobSmyDscTe { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string JobClsCd { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string RecEffSttDt { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string RecStsCd { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string JobClsCdDscTe { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string JobFctCd { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string PayBssTypCd { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string EmpOpTypCd { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string JobUnnEmpReqIr { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string JobPhyExmReqIr { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string JobSafAwdElgIr { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string JobEocOccCgyCd { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string JobGrpCd { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string EmpFlsJobClsCd { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string CdaNtlOccCsfCd { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string WagCd { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string BsuGrpTe { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string MgrLvlCd { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string JtlAbrNa { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public string JobSmyDscTe { get; set; }

	}
}

