//       Autogenerated Class From XMLToModel         //
using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml;
using HubXLookUps;


namespace HubXLookUps
{
	/// <summary>
	/// 
	/// </summary>
	public class EmployeeJobCodes
	{
		/// <summary>
		/// 
		/// </summary>
		public List<EmployeeJobCodes> LoadJobCodes(string xmlFilePath)
		{
			List<EmployeeJobCodes> objCol = new List <EmployeeJobCodes>();
			XmlDocument xDoc = new XmlDocument();
			xDoc.Load(xmlFilePath);
			XmlNodeList xnList = xDoc.SelectNodes("/main/DATA_RECORD");
			foreach (XmlNode xn in xnList)
			{
				EmployeeJobCodes obj = new EmployeeJobCodes();
				obj.JobClsCd = xn["JOB_CLS_CD"].InnerText;
				obj.RecEffSttDt = xn["REC_EFF_STT_DT"].InnerText;
				obj.RecStsCd = xn["REC_STS_CD"].InnerText;
				obj.JobClsCdDscTe = xn["JOB_CLS_CD_DSC_TE"].InnerText;
				obj.JobFctCd = xn["JOB_FCT_CD"].InnerText;
				obj.PayBssTypCd = xn["PAY_BSS_TYP_CD"].InnerText;
				obj.EmpOpTypCd = xn["EMP_OP_TYP_CD"].InnerText;
				obj.JobUnnEmpReqIr = xn["JOB_UNN_EMP_REQ_IR"].InnerText;
				obj.JobPhyExmReqIr = xn["JOB_PHY_EXM_REQ_IR"].InnerText;
				obj.JobSafAwdElgIr = xn["JOB_SAF_AWD_ELG_IR"].InnerText;
				obj.JobEocOccCgyCd = xn["JOB_EOC_OCC_CGY_CD"].InnerText;
				obj.JobGrpCd = xn["JOB_GRP_CD"].InnerText;
				obj.EmpFlsJobClsCd = xn["EMP_FLS_JOB_CLS_CD"].InnerText;
				obj.CdaNtlOccCsfCd = xn["CDA_NTL_OCC_CSF_CD"].InnerText;
				obj.WagCd = xn["WAG_CD"].InnerText;
				obj.BsuGrpTe = xn["BSU_GRP_TE"].InnerText;
				obj.MgrLvlCd = xn["MGR_LVL_CD"].InnerText;
				obj.JtlAbrNa = xn["JTL_ABR_NA"].InnerText;
				obj.JobSmyDscTe = xn["JOB_SMY_DSC_TE"].InnerText;
				obj.JobClsCd = xn["JOB_CLS_CD"].InnerText;
				obj.RecEffSttDt = xn["REC_EFF_STT_DT"].InnerText;
				obj.RecStsCd = xn["REC_STS_CD"].InnerText;
				obj.JobClsCdDscTe = xn["JOB_CLS_CD_DSC_TE"].InnerText;
				obj.JobFctCd = xn["JOB_FCT_CD"].InnerText;
				obj.PayBssTypCd = xn["PAY_BSS_TYP_CD"].InnerText;
				obj.EmpOpTypCd = xn["EMP_OP_TYP_CD"].InnerText;
				obj.JobUnnEmpReqIr = xn["JOB_UNN_EMP_REQ_IR"].InnerText;
				obj.JobPhyExmReqIr = xn["JOB_PHY_EXM_REQ_IR"].InnerText;
				obj.JobSafAwdElgIr = xn["JOB_SAF_AWD_ELG_IR"].InnerText;
				obj.JobEocOccCgyCd = xn["JOB_EOC_OCC_CGY_CD"].InnerText;
				obj.JobGrpCd = xn["JOB_GRP_CD"].InnerText;
				obj.EmpFlsJobClsCd = xn["EMP_FLS_JOB_CLS_CD"].InnerText;
				obj.CdaNtlOccCsfCd = xn["CDA_NTL_OCC_CSF_CD"].InnerText;
				obj.WagCd = xn["WAG_CD"].InnerText;
				obj.BsuGrpTe = xn["BSU_GRP_TE"].InnerText;
				obj.MgrLvlCd = xn["MGR_LVL_CD"].InnerText;
				obj.JtlAbrNa = xn["JTL_ABR_NA"].InnerText;
				obj.JobSmyDscTe = xn["JOB_SMY_DSC_TE"].InnerText;
				objCol.Add(obj);
			}
			return objCol;
		}
	}
}


